### ISSUE TITLE
it trows an error on startup

### ISSUE THREAD

**Issue by talamaska** [tjwebb/sails-swagger#15]
``` terminal
The bootstrap function threw an error after its callback was called :: TypeError: Invalid attempt to destructure non-iterable instance
    at server-location\node_modules\sails-swagger\dist\lib\xfmr.js:7:586
    at Object.getControllerFromRoute (server-location\node_modules\sails-swagger\dist\lib\xfmr.js:208:29)
    at Object.getPathTags (server-location\node_modules\sails-swagger\dist\lib\xfmr.js:178:183)
    at Object.getOperation (server-location\node_modules\sails-swagger\dist\lib\xfmr.js:169:25)
    at server-location\node_modules\sails-swagger\dist\lib\xfmr.js:155:26
    at server-location\node_modules\lodash\index.js:3395:24
    at server-location\node_modules\lodash\index.js:3073:15
    at baseForOwn (server-location\node_modules\lodash\index.js:2046:14)
    at Function.mapValues (server-location\node_modules\lodash\index.js:3394:9)
    at Object.getPathItem (server-location\node_modules\sails-swagger\dist\lib\xfmr.js:154:32)
    at server-location\node_modules\sails-swagger\dist\lib\xfmr.js:113:26
    at server-location\node_modules\lodash\index.js:3395:24
    at server-location\node_modules\lodash\index.js:3073:15
    at baseForOwn (server-location\node_modules\lodash\index.js:2046:14)
    at Function.mapValues (server-location\node_modules\lodash\index.js:3394:9)
    at Object.getPaths (server-location\node_modules\sails-swagger\dist\lib\xfmr.js:112:32) [TypeError: Invalid attempt to destructure non-iterable instance]
```

What I'm doing wrong?

**Comment by zontafil** [comment]
similar problem:

```
  error: The bootstrap function threw an error after its callback was called :: ReferenceError: Symbol is not defined
      at Object.getPathControllerTag (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:226:51)
      at Object.getPathTags (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:211:129)
      at Object.getOperation (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:200:25)
      at /home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:186:26
      at /home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:3395:24
      at /home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:3073:15
      at baseForOwn (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:2046:14)
      at Function.mapValues (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:3394:9)
      at Object.getPathItem (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:185:32)
      at /home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:142:26
      at /home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:3395:24
      at /home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:3073:15
      at baseForOwn (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:2046:14)
      at Function.mapValues (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/node_modules/lodash/index.js:3394:9)
      at Object.getPaths (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:141:32)
      at Object.getSwagger (/home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/lib/xfmr.js:66:26)
      at /home/dati/Sorgenti/Node/d/node_modules/sails-swagger/dist/api/hooks/swagger/index.js:77:41
      at /home/dati/Sorgenti/Node/d/node_modules/sails/lib/app/private/after.js:91:14
      at /home/dati/Sorgenti/Node/d/node_modules/sails/node_modules/async/lib/async.js:251:17
      at done (/home/dati/Sorgenti/Node/d/node_modules/sails/node_modules/async/lib/async.js:132:19)
      at /home/dati/Sorgenti/Node/d/node_modules/sails/node_modules/async/lib/async.js:32:16
      at /home/dati/Sorgenti/Node/d/node_modules/sails/node_modules/async/lib/async.js:248:21 [ReferenceError: Symbol is not defined]
```

**Comment by prasad-1210** [comment]
same issue

debug: --------------------------------------------------------
debug: :: Thu Dec 17 2015 11:29:49 GMT+0000 (UTC)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
error: The bootstrap function threw an error after its callback was called :: TypeError: Cannot set property 'doc' of undefined
    at /opt/node/sails/app8/swagger/swagg/node_modules/sails-swagger/dist/api/hooks/swagger/index.js:49:18
    at /usr/local/lib/node_modules/sails/lib/app/private/after.js:91:14
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:251:21
    at Sails.<anonymous> (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:575:34)
    at Sails.g (events.js:199:16)
    at Sails.emit (events.js:129:20)
    at Sails.emitter.emit (/usr/local/lib/node_modules/sails/lib/app/private/after.js:50:11)
    at sailsReady (/usr/local/lib/node_modules/sails/lib/app/lift.js:47:11)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:615:34
    at afterBootstrap (/usr/local/lib/node_modules/sails/lib/app/private/initialize.js:57:5) [TypeError: Cannot set property 'doc' of undefined]

**Comment by zuker** [comment]
This happens when `controller` property in route config don't match pattern here https://github.com/tjwebb/sails-swagger/blob/v0.5.1/lib/xfmr.js#L188.

**Comment by talamaska** [comment]
Well, so we must name our controllers properly. But interesting is on https://github.com/tjwebb/sails-swagger/blob/v0.5.1/lib/xfmr.js#L193 that this pattern variable is never used.

**Comment by zuker** [comment]
Yes, variable `pattern` is never used, but the same pattern `/(.+)Controller/` is used here: https://github.com/tjwebb/sails-swagger/blob/v0.5.1/lib/xfmr.js#L193

**Comment by talamaska** [comment]
You're right but this logic doesn't correspond to the Sails docs about custom routes
http://sailsjs.org/documentation/concepts/routes/custom-routes

```
'GET /foo/go': 'FooController.myGoAction',
'GET /foo/go': 'Foo.myGoAction',
'GET /foo/go': {controller: "Foo", action: "myGoAction"},
'GET /foo/go': {controller: "FooController", action:"myGoAction"},
```

so this plugin will detect only the last route?

**Comment by zuker** [comment]
It seems that yes: only controllers specified by `globalId` (i.e. `controller: "FooController"`) in route configuration are detected properly.

**Comment by thibaultboursier** [comment]
Same problem, I had to add "Controller" suffix on controller property to make it working.
