### ISSUE TITLE
Cannot read property 'pkg' of undefined

### ISSUE THREAD

**Issue by davidportella** [tjwebb/sails-swagger#9]
Using:

``` bash
✔ ~/PhpstormProjects/backoffice [master|●2✚ 2]
10:41 $ npm --version
3.3.5
✔ ~/PhpstormProjects/backoffice [master|●2✚ 2]
10:42 $ node --version
v4.1.2
✔ ~/PhpstormProjects/backoffice [master|●2✚ 2]
10:42 $ sails --version
0.11.0
```

I have this error:

``` javascript
info: Starting app...

debug: hookPath: /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/hooks/swagger
debug: marlinspike (swagger): loading config from /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/config
debug: marlinspike (swagger): loading Services from /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/services...
info: Error: ENOENT: no such file or directory, scandir '/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/services'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at requireAll (/Users/davidportella/PhpstormProjects/backoffice/node_modules/marlinspike/node_modules/require-all/index.js:12:18)
    at Swagger.loadServices (/Users/davidportella/PhpstormProjects/backoffice/node_modules/marlinspike/dist/marlinspike.js:129:52)
    at Hook.configure (/Users/davidportella/PhpstormProjects/backoffice/node_modules/marlinspike/dist/marlinspike.js:198:51)
    at Hook.bound [as configure] (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/loadHooks.js:176:18
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:122:13
    at _each (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:121:9)
    at Object.async.series.configure (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/loadHooks.js:174:17)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:620:25
    at iterate (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:146:13)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:626:21
    at done (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:132:19) { [Error: ENOENT: no such file or directory, scandir '/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/services']
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/services' }
warn: marlinspike (swagger): no Services found. skipping
debug: marlinspike (swagger): loading Controllers...
debug: marlinspike (swagger): loading Policies...
info: Error: ENOENT: no such file or directory, scandir '/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/policies'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at requireAll (/Users/davidportella/PhpstormProjects/backoffice/node_modules/marlinspike/node_modules/require-all/index.js:12:18)
    at Swagger.loadPolicies (/Users/davidportella/PhpstormProjects/backoffice/node_modules/marlinspike/dist/marlinspike.js:93:52)
    at Hook.configure (/Users/davidportella/PhpstormProjects/backoffice/node_modules/marlinspike/dist/marlinspike.js:201:51)
    at Hook.bound [as configure] (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/loadHooks.js:176:18
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:122:13
    at _each (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:121:9)
    at Object.async.series.configure (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/loadHooks.js:174:17)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:620:25
    at iterate (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:146:13)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:626:21
    at done (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:132:19) { [Error: ENOENT: no such file or directory, scandir '/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/policies']
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/policies' }
warn: marlinspike (swagger): no Policies found. skipping
info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `/Users/davidportella/PhpstormProjects/backoffice`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Wed Oct 28 2015 10:41:26 GMT-0300 (CLT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
error: The bootstrap function threw an error after its callback was called :: TypeError: Cannot read property 'pkg' of undefined
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails-swagger/dist/api/hooks/swagger/index.js:49:91
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/after.js:91:14
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:251:17
    at done (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:132:19)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:32:16
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:248:21
    at Sails.<anonymous> (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:572:34)
    at Sails.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Sails.emit (events.js:166:7)
    at Sails.emitter.emit (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/after.js:50:11)
    at sailsReady (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/lift.js:47:11)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:251:17
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:154:25
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:612:34
    at afterBootstrap (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/initialize.js:57:5)
    at bootstrapDone (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/bootstrap.js:51:14)
    at Object.module.exports.bootstrap (/Users/davidportella/PhpstormProjects/backoffice/config/bootstrap.js:2:5)
    at Sails.runBootstrap (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Sails.initialize (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/private/initialize.js:48:9)
    at bound (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:607:21
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:246:17
    at iterate (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:146:13)
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:612:34
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/lib/app/load.js:201:13
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/Users/davidportella/PhpstormProjects/backoffice/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:374:17) [TypeError: Cannot read property 'pkg' of undefined]
```

**Comment by tjwebb** [comment]
Did you do this? https://github.com/tjwebb/sails-swagger#configuration
